version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sre-bootcamp-api-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ytatom0byspe"
s3_prefix = "sre-bootcamp-api-aws"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true
