version: '3.7'

services:
  app:
    container_name: express-app
    restart: always
    image: truji96/academy-sre-bootcamp-adrian-trujillo:latest
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
